networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  jenkins:
    image: myjenkins/blueocean:2.387.3
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      custom:
        ipv4_address: 192.168.61.15
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: jenkins
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - docker

  docker:
    image: docker:dind
    ports:
      - 2376:2376
      - 8888:8888
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      custom:
        ipv4_address: 192.168.61.16
        aliases:
          - docker
    privileged: true
    domainname: codespaces.io
    hostname: docker
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

