version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes:
  cs-ansible:

services:
  control:
    image: codespaces/ansible-control:v1.0
    ports:
      - "8000:8000"
    volumes:
      - cs-ansible:/workspace
    networks:
      custom:
        ipv4_address: 192.168.61.10
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: control
    restart: always
  frontend:
    image: codespaces/ansible-node-ubuntu-1404:v0.1.0
    ports:
       - "80:8079"
    networks:
      custom:
        ipv4_address: 192.168.61.11
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: frontend
    restart: always
  catalogue:
    image: codespaces/ansible-node-ubuntu-1404:v0.1.0
    ports:
       - "7081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.12
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: catalogue
    restart: always
  carts:
    image: codespaces/ansible-node-ubuntu-1404:v0.1.0
    ports:
      - "8081:80"
    networks:
      custom:
        ipv4_address: 192.168.61.13
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: carts
    restart: always
  carts-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      custom:
        ipv4_address: 192.168.61.15
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: jenkins
    restart: always
